//
// Created by David on 05/07/2025.
//

#ifndef PARTICLES_UNIFORMS_H
#define PARTICLES_UNIFORMS_H

#define LIGHT_BINDING_POINT 1
#define MATERIAL_BINDING_POINT 2
#define MATRICES_BINDING_POINT 3

#endif //PARTICLES_UNIFORMS_H
